main: com.linmalu.randombox.Main
name: LinmaluRandomBox
version: 1.13.2.0
author: 린마루(Linmalu)
website: http://blog.linmalu.com/
description: LinmaluRandomBox
depend: [LinmaluLibrary]

commands:
    LinmaluRandomBox:
        description: 랜덤상자 플러그인
        aliases: [lrb, 랜덤상자]
        usage: '명령어 : /<command>'
